[package]
name = "kafi"
version = "0.1.0"
authors = ["robin <r@nosql.asia"]
description = "Simple persistent key value store library for Rust."
license = "MIT"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
bincode = "0.9.2"
